# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
a = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
b = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
b.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
b.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Hasnain Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Syed Hasnain Ali/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Hasnain Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_li

7. Print the dimension of the array in question 3


In [6]:
b.ndim

1

8. Create a boolean array with all the True values

In [7]:
np.ones((2, 2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [13]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:
d = np.arange(1, 10)
e = d[::-1]
e

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
c = np.zeros(10)
c[4] = 1
c

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [8]:
arry=np.identity(3)
arry

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [9]:
ary = np.array([1, 2, 3, 4, 5]) 
ary = ary.astype('float64') 
ary.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [11]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
    
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
res = arr1*arr2
res


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [12]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
res = arr1 == arr2
res

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [14]:
d = np.arange(1, 10)
odd = (d%2 == 1)
d[odd]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [15]:
d = np.arange(1, 10)
odd = (d%2 == 1)
d[odd] = -1
d

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [17]:
arr = np.arange(10)
print(arr)
arr[5] =12
arr[6] =12
arr[7] =12
arr[8] =12
arr


[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [18]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [19]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:-1,1:-1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [20]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:-1,:-1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [37]:
a = np.arange(0,10).reshape(5,2)
print(a)
res = a[0:1:1]
res

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[0, 1]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
a = np.arange(0,10).reshape(2,5)
print(a)
res = a[1:2:,1:2:]
res

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [42]:
a = np.arange(0,10).reshape(2,5)
print(a)
res = a[0:2:,3:4:]
res

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[3],
       [8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
x = np.random.randn(10,10)
print(np.max(x))
print(np.min(x))

2.9853148365753546
-1.9936649094918772


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names != 'Will')
data[names != 'Will']

[ True  True False  True False  True  True]


array([[-0.14023681, -1.72056078, -0.63197225, -0.42187428],
       [-0.30731082, -0.09537999,  1.06604605, -0.14483851],
       [-1.32062673,  0.3634025 , -0.33991795, -0.41858945],
       [-0.90240478,  2.24114384, -0.18380658, -0.90456961],
       [ 0.79414609,  1.95276871,  2.64089878,  0.29645574]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
print(mask)
data[mask]

[ True False False  True False False False]


array([[ 0.66912751, -0.51161677,  0.65329912,  1.12438268],
       [-2.41961011,  0.19382606,  0.40706747, -0.50641985]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [41]:
rand_arr = np.arange(1,16).reshape(5,3)
rand_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [43]:
rand_arr = np.arange(1,17).reshape(2,2,4)
rand_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [52]:
#np.swapaxes(rand_arr, 2, 0)
rand_arr.transpose()

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [59]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
sqrot = np.sqrt(arr)
sqrot
np.where(sqrot<0.5,0,sqrot)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [31]:
a = np.random.randn(12)
print(a)
b = np.random.randn(12)
print(b)
res = np.maximum(a,b)
print('Result Array')
print(res)

[-2.32062166  0.35542617 -0.13230032 -0.04146539  0.97778441  0.80699053
  0.22271881 -0.51635049  0.52767153  1.56728919  0.84241321  0.25289129]
[ 1.01951883  0.90101834 -0.64274876 -1.606789    0.31120332  1.81527923
  0.24912935  0.1203894   1.81158792 -0.53960599 -0.09979688  0.32103393]
Result Array
[ 1.01951883  0.90101834 -0.13230032 -0.04146539  0.97778441  1.81527923
  0.24912935  0.1203894   1.81158792  1.56728919  0.84241321  0.32103393]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
res = np.unique(names)
print(res)
print('Sorting Array')
res1 = np.sort(res)
res1

['Bob' 'Joe' 'Will']
Sorting Array


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [12]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
res = np.setdiff1d(a, b)
res

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [15]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print('Original Array')
print(sampleArray)
sampleArray = np.delete(sampleArray , 1, axis = 1)
print('Column Deleted')
print (sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1)
print('Modified Array')
print (sampleArray)

Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Column Deleted
[[34 73]
 [82 12]
 [53 66]]
Modified Array
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [16]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
res = np.dot(x,y)
res

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [25]:
#Z = np.random.random(20)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr
res = np.cumsum(arr)
res

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210], dtype=int32)