# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
arr1 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
arr1 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
arr = np.array([[ 0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [10]:
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
arr.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
arr = np.arange(0,25).reshape(5,5)
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [20]:
arr1 = np.arange(0,30).reshape(5,6)
print(arr1)
print(np.mean(arr1))
print(np.mean(arr1, axis =0))
print(np.mean(arr1, axis =1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
14.5
[12. 13. 14. 15. 16. 17.]
[ 2.5  8.5 14.5 20.5 26.5]


## Question:9

### Find the standard deviation of the previous array in Q8?

In [43]:
print(np.std(arr1))
print('Standard deviation along axis 0 is as follow...')
print(np.std(arr1, axis =0))
print('Standard deviation along axis 1 is as follow...')
print(np.std(arr1, axis =1))

8.65544144839919
Standard deviation along axis 0 is as follow...
[8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]
Standard deviation along axis 1 is as follow...
[1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]


## Question:10

### Find the median of the previous array in Q8?

In [21]:
print(arr1)
print(np.median(arr1))
print(np.median(arr1, axis =0))
print(np.median(arr1, axis =1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
14.5
[12. 13. 14. 15. 16. 17.]
[ 2.5  8.5 14.5 20.5 26.5]


## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
print(arr1)
print('transpose of mentioned array is as follow')
print(arr1.transpose())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
transpose of mentioned array is as follow
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
ar1 = np.array([[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]])
print(ar1)
print('sum of diagonal elements is')
print(np.trace(ar1))
# Same can be done using Diagonal Function to get diagonal elements and then sum those elements
#res = np.diagonal(ar)
#print(res)
#print(sum(res))

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
sum of diagonal elements is
20


## Question:13

### Find the determinant of the previous array in Q12?

In [35]:
print(np.linalg.det(ar1))

2.070759876205155e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [39]:
x = np.array([[10,20,30],[20,30,40],[30,40,50]])
print(x)
print('5th percentile of the mentioned array is')
print(np.percentile(x,5))
print('95th percentile of the mentioned array is')
print(np.percentile(x,95))

[[10 20 30]
 [20 30 40]
 [30 40 50]]
5th percentile of the mentioned array is
14.0
95th percentile of the mentioned array is
46.0


## Question:15

### How to find if a given array has any null values?

In [72]:
#x = np.array([[10,20,30],[20,30,40],[30,40,50]])
x = np.empty((0,1))
print("Original array:")
print(x)
print("\nTest whether the said array has null columns or not:")
print((~x.any(axis=0)).any())

Original array:
[]

Test whether the said array has null columns or not:
True
